# coding: utf-8

"""
    Hello World API

    A simple API for saying hello and managing person names.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Hello World API",
    description="A simple API for saying hello and managing person names.",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
